# Re-exportamos todos los repositorios para mantener compatibilidad hacia atrás
from app.infrastructure.repositories.user_repository import PostgresUserRepository
from app.infrastructure.repositories.jugada_repository import PostgresJugadaRepository
from app.infrastructure.repositories.post_repository import PostgresPostRepository
from app.infrastructure.repositories.publicidad_repository import PostgresPublicidadRepository
from app.infrastructure.repositories.transaction_repository import PostgresTransactionRepository
from app.infrastructure.repositories.notification_repository import PostgresNotificationRepository
