name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure correct source branch based on destination
        run: |
          # Si el destino es main, la rama de origen debe ser dev
          if [ "${{ github.base_ref }}" = "main" ] && [ "${{ github.head_ref }}" != "dev" ]; then
            echo "ERROR: Solo se permiten Pull Requests hacia 'main' si provienen de la rama 'dev'."
            exit 1
          fi
